site_name: py-ISPyB
nav:
    - Home: index.md
    - Running: run.md
    - Authentication and authorization: auth.md
    - Routes: routes.md
    - Tests: tests.md
theme:
    name: material
site_dir: public
site_url: https://ispyb.github.io/py-ispyb/
repo_url: https://github.com/ispyb/py-ispyb
repo_name: "GitHub"
markdown_extensions:
    - toc:
          permalink: "#"
dev_addr: "127.0.0.1:8080"
